name: wtf
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter_animate:
  get: ^4.6.5
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  dio: any
  shared_preferences: ^2.1.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

