import 'package:get/get.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:wtf/app/api.dart';

import '../../../model.dart';


class PickLocationController extends GetxController {

  final data = Rxn<Autogenerated?>();
  final lat = Rxn<double?>();
  final long = Rxn<double?>();

  init() async {
    final SharedPreferences prefs = await SharedPreferences.getInstance();

    final List<String>? items = prefs.getStringList('location');
    if (items != null) {
      lat.value = double.parse(items[0]);
      long.value = double.parse(items[1]);
    }
    if (lat.value != null && long.value != null) {
      data.value = await getGymData(1, 30, lat.value!, long.value!);
    }
  }


  getLocationFromLocalStorage() async {
    final SharedPreferences prefs = await SharedPreferences.getInstance();

    final List<String>? items = prefs.getStringList('location');
    if (items != null) {

      lat.value = double.parse(items[0]);
      long.value = double.parse(items[1]);
    }
  }

  setLocationToLocalStorage(double lat, double long) async {
    final SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.setStringList('location', [lat.toString(), long.toString()]).whenComplete(() => getLocationFromLocalStorage()
    );


  }

  @override
  void onInit() {
    super.onInit();
    init();
  }

  @override
  void onReady() {
    super.onReady();
  }

  @override
  void onClose() {
    super.onClose();
  }
}
